### ISSUE TITLE
Peer review - feedback 19 maart

### ISSUE THREAD

**Issue by Chazzers** [veerleprins/progressive-web-apps-2021#12]
# Repo

- Nette folder structuur! Een alternatief hiervoor wat wel eens gebruikt wordt in het werkveld is MVC(Models, Views, Controllers), Je zou hiernaar kunnen kijken als je dat leuk vind

# Code

- Ziet er goed uit!!

**Comment by veerleprins** [comment]
Thanks for the feedback! Indeed I have heard of MVC model before, but will continue to work with this project with my structure 😄.
