### ISSUE TITLE
Peer Review week 1

### ISSUE THREAD

**Issue by SharonV33** [veerleprins/progressive-web-apps-2021#3]
## repo and project structure 🤓 
Live link werkt nog niet helemaal lekker, als ik vanaf een detail pagina naar een andere film wil krijg ik een error.  Verder wel al de key features van je app erin, lekker bezig! 👍🏻  readme is lekker duidelijk, makkelijk te volgen installatie instructies 😃  Repo bevat geen node_modules en is goed overzichtelijk!

## node.js implementatie 
Alle key features zijn al omgebouwd naar node.js, nice ⭐  nauwelijks tot geen comments maar dat is misschien ook een beetje persoonlijke voorkeur 😅  Verder ziet het er naar uit dat je goet weet wat je doet en hoe node werkt

verder, eujm ja chill project lekker bezig 🎆

**Comment by veerleprins** [comment]
Thanks for the feedback! In the meantime I have adjusted a few things to make the site work 😄 👍
