### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by victorboucher** [veerleprins/progressive-web-apps-2021#4]
## Readme
Je readme is al erg uitgebreid, erg nice ook hoe je super uitgebreid uitlegt hoe je alles moet installeren. Hier heb ik op dit moment verder niet echt iets op aan te merken

## Code
- Je structuur is erg netjes, je hebt je router opgedeeld in een apart bestand en al je routes in aparte files. Dit is erg handig en zorgt ervoor dat je project overzichtelijk blijft.
- Volgens mij heb je al zo goed als je hele WAFS app herschreven om met een Express backend te laten werken, ziet er netjes uit.
- Je hebt je API key bijvoorbeeld al in een .env bestand staan, dit is ook erg handig want zo kan niemand zomaar je API key gebruiken.
- Ik gebruik zelf altijd app.use(router) ipv app.use("/", router(of routes in jouw geval)), ik weet niet zo goed wat hier anders aan is, maar het lijkt alsof je hier al iets doet met je main index route. Misschien is dit overbodig?
- In je routes.js bestand importeer je de verschillende routes op deze manier: const { home } = require .... Je kunt dit ook exporteren zonder de brackets en dan weer importeren zonder de brackets. Dat is wat netter vind ik.
- Je zou kunnen kijken of het netter is om je routes en variabelen soortvan te 'chainen', dat zou er dan zo uit zien:
```javascript
router
    .get("/", home)
    .get("/:id", movie)
    // etc...
```

Ik heb verder niet echt iets aan te merken op je code, ziet er goed uit en je bent al best ver! Lekker bezig, ga zo door 🥇

**Comment by veerleprins** [comment]
Thank you for the good feedback! In my develop branch (and final code) I applied the feedback to my code. 👍 😄
