### ISSUE TITLE
Peer Review - Week #2 - Repository 

### ISSUE THREAD

**Issue by lisaoude** [veerleprins/progressive-web-apps-2021#7]
### General
- You have added a great description at the top right of your repository, including what you worked with to make your app ✔️🔥 
- Clear commit messages 👏 
- Great folder structure 🔥 

---

### Readme
- Great short description added. It tell me why you made your app and gives an introduction on how you made it! 😄 
- API is well described 🔥
- Installing is described well!
- Live link can be added at the 'deploy' section of you readme as well 😄 
- You've started a place to gather your sources, but its looking a little empty 👀 
- License was added, but your name is missing on the file, plus it doesn't like to the right page (copy and paste from the previous project? 😆 )
- A mockup picture would've taken your readme to the next step! 📈 
- It might be nice to describe your packages a bit more and explain why you use each one 🔍 

---

*Nice work, keep it up 🔥*

--- 

## To Solve This Issue
- [x] Add live link to 'deploy' section in readme
- [x] Add sources to the 'sources' section in your readme
- [x] Add your own name to the license file
- [x] Change link to correct lincense file
- [x] Add a nice mockup picture to your readme
- [x] Describe and explain used packages

**Comment by veerleprins** [comment]
Thanks for the feedback 👍 😄
