### ISSUE TITLE
Peer Review - Week #2 - JS Code

### ISSUE THREAD

**Issue by lisaoude** [veerleprins/progressive-web-apps-2021#8]
## Review
- Your code looks very clean and organized! 🧹 
- Nice and short app.js, because you're linking to a separate routes file! 🥇 
- Little trick I learned from a tutorial: you can actually leave out the following line of code, as long as you make sure the folder you use is still called views:

```js
app.set("views", "views");
```

- Routes file looks very clean too and is easily understandable 🔥
- You eventually could split up the getting data, cleaning data and rendering of your pages (all @ renders) into separate files, so it all becomes even cleaner ➕🧹 

---

*Looking cleeeaaan 🧹🔥*

--- 

## To Solve This Issue - *If you'd like to*
- [x] Remove 'unnecessary' line of code
- [ ] Split up getting data, cleaning data & rendering of the pages into separate files

**Comment by veerleprins** [comment]
"Split up getting data, cleaning data & rendering of the pages into separate files". I already do this at the moment 😉 . In addition, it should not become a waterfall effect! But thanks for the feedback 👍 😄
